openapi: 3.1.0
info:
  version: 1.3.15
  title: Payrails API Reference
  contact:
    name: Payrails
    url: https://www.payrails.com
    email: tech@payrails.com
  license:
    name: Payrails GmbH
    url: https://www.payrails.com/
  description: |
    ---
    Payrails provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes. You can consume the APIs directly using your favorite HTTP/REST library.
servers:
  - url: https://api.staging.payrails.io
    description: Payrails environment.
security:
  - ApiKey: []
tags:
  - name: APILogs
    description: API Logs.
paths:
  /payment/api/logs:
    get:
      summary: Search & list API Logs
      operationId: apilogs
      description: Fetch a list of API Logs for the given query parameters.
      tags:
        - APILogs
      security:
        - BearerToken:
            - apilogs:list
      parameters:
        - name: filter[requestId]
          in: query
          schema:
            type: string
          description: Filter for a list of API log event by requestID.
        - name: filter[endpointUrl]
          in: query
          schema:
            type: string
          description: Filter for a list of API log event by endpoint URL.
        - name: filter[statusCode]
          in: query
          schema:
            type: string
          description: Filter for a list of API log event by response status code.
        - name: filter[method]
          in: query
          schema:
            type: string
          description: Filter for a list of API log event by HTTP method.
        - name: filter[createdAt]
          in: query
          description: |
            Filter by `createdAt` field using interval notation.

            `1973-02-03T04:32:11.596Z` - exact date value

            `(1973-02-03T04:32:11.596Z` - after the date excluding it

            `[1973-02-03T04:32:11.596Z` - after the date including it

            `1973-02-03T04:32:11.596Z)` - before the date excluding it

            `1973-02-03T04:32:11.596Z]` - before the date including it

            `(1973-02-03T04:32:11.596Z,1973-04-03T03:20:11.436Z)` - between two dates excluding both

            `(1973-02-03T04:32:11.596Z,1973-04-03T03:20:11.436Z]` - between two dates excluding on the left

            `[1973-02-03T04:32:11.596Z,1973-04-03T03:20:11.436Z)` - between two dates excluding on the right

            `[1973-02-03T04:32:11.596Z,1973-04-03T03:20:11.436Z]` - between two dates including both.
          schema:
            type: string
            example: '[2026-04-01T00:00:00Z,2026-05-01T00:00:00Z)'
        - name: page[cursor]
          in: query
          description: Search collection items from that cursor.
          required: false
          schema:
            type: string
            description: Cursor for paging results.
          example: 9wkueqcavq
        - name: page[after]
          in: query
          description: Search collection items after that cursor.
          required: false
          schema:
            type: string
            description: Cursor for paging results.
          example: xk2h55zsy5
        - name: page[before]
          in: query
          description: Search collection items before that cursor.
          required: false
          schema:
            type: string
            description: Cursor for paging results.
          example: 9wkueqcavq
        - name: page[size]
          in: query
          description: Length of the collection to search.
          required: false
          schema:
            type: integer
            format: int32
          example: 20
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  paging:
                    type: object
                    description: Paging information about the results.
                    properties:
                      next:
                        type: string
                        example: '?createdAtOrAfter=2022-02-11+00%3A00%3A00&createdAtOrBefore=2022-02-11+20%3A17%3A52.885&limit=50'
                  results:
                    type: array
                    description: List of results for the query.
                    items:
                      type: object
                      description: For some API endpoint we provide we do log request and response.
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the API Log event in Payrails.
                        createdAt:
                          type: string
                          format: date-time
                          description: Exact date and time when the API Log event happened.
                        requestID:
                          type: string
                          format: uuid
                          description: Unique identifier of the API request.
                        method:
                          type: string
                          description: Request HTTP method.
                        statusCode:
                          type: number
                          description: Response HTTP code number.
                        rawRequest:
                          type: string
                          description: Serialized raw request.
                        rawResponse:
                          type: string
                          description: Serialized raw response.
              example:
                links:
                  first: https://api.staging.payrails.io/payment/api/logs
                  self: https://api.staging.payrails.io/payment/api/logs
                results:
                  - id: 080405df-b575-4106-9ff6-5cceafc35445
                    requestId: 0412ee01-d3e6-4cb7-a29f-e91721b0b62b
                    createdAt: '2023-05-23T14:12:40.444493Z'
                    endpointUrl: /payment/providers/070dacf4-ddd8-42cd-87ec-944ebf1adc41/proxy
                    statusCode: 404
                    method: POST
                    rawRequest: '{"body":{"body":{"amount":{"currency":"USD","value":1000},"merchantAccount":"YOUR_MERCHANT_ACCOUNT","paymentMethod":{"cvc":"***","expiryMonth":"{{expiryMonth}}","expiryYear":"{{expiryYear}}","holderName":"{{holderName}}","number":"***","type":"scheme"},"reference":"your-order-number","returnUrl":"https://your-company.com/..."},"headers":{"Accept":"application/json","Content-Type":"application/json","x-API-key":"YOUR_API_KEY"},"paymentInstrumentId":"eeaac45c-f032-49bc-a8c5-ec99d79b74e2","providerConfigId":"d9699acd-9361-4e11-8d06-b30f41fc6210"},"headers":{"Accept":"application/json","Accept-Encoding":"gzip","Authorization":"***","Cdn-Loop":"cloudflare","Cf-Connecting-Ip":"18.196.176.219","Cf-Ipcountry":"DE","Cf-Ray":"7cbde527aed4bbd9-FRA","Cf-Visitor":{"scheme":"https"},"Ckoidempotencykey":"application/json","Content-Length":"706","Content-Type":"application/json","Postman-Token":"bfa62b82-5026-4bb3-9b57-0930f287fccc","True-Client-Ip":"18.196.176.219","User-Agent":"PostmanRuntime/7.29.3","X-Forwarded-For":"172.70.247.146","X-Forwarded-Host":"payrails-api.staging.payrails.io","X-Forwarded-Port":"443","X-Forwarded-Proto":"https","X-Forwarded-Scheme":"https","X-Idempotency-Key":"5ff04085-beae-4d41-ba78-73eb918d8e7c","X-Original-Forwarded-For":"18.196.176.219","X-Real-Ip":"172.70.247.146","X-Request-Id":"0412ee01-d3e6-4cb7-a29f-e91721b0b62b","X-Scheme":"https","Xapikey":"application/json"}}'
                    rawResponse: '{"body":{"errors":[{"detail":"The resource with ''Payment instrument ID'': ''eeaac45c-f032-49bc-a8c5-ec99d79b74e2'' was not found.","id":"6a1456fc-13cf-4b8a-a75e-3891d86873a0","title":"resource.not-found"}]},"headers":{"Content-Type":"application/json; charset=UTF-8","X-Request-Id":"0412ee01-d3e6-4cb7-a29f-e91721b0b62b"}}'
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.malformed
                    detail: The request has malformed syntax
                    docUrl: https://docs.payrails.com/docs/error-codes#requestmalformed
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.unauthorized
                    detail: The request lacks necessary credentials to perform the specified action
                    docUrl: https://docs.payrails.com/docs/error-codes#requestunauthorized
        '403':
          description: Insufficient Scope.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: e7db22b3-914e-4975-928e-9edfb0885bea
                    code: request.forbidden
                    detail: The request credentials lack the required permissions to perform the specified action
                    docUrl: https://docs.payrails.com/docs/error-codes#requestforbidden
        '429':
          description: Too Many Requests.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.rate-limit
                    detail: Too many requests
                    docUrl: https://docs.payrails.com/docs/error-codes#requestrate-limit
  /payment/api/logs/{apiLogEventId}:
    get:
      tags:
        - APILogs
      summary: Get an API Log event by ID
      description: Get API Log event by ID.
      operationId: getAPILogEvent
      security:
        - BearerToken:
            - apilogs:read
      parameters:
        - name: apiLogEventId
          in: path
          description: Identifier of the resource in Payrails.
          required: true
          schema:
            type: string
            format: uuid
          example: d5454c2f-ae5e-44f3-8edf-f6dad64f005f
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                type: object
                description: For some API endpoint we provide we do log request and response.
                properties:
                  id:
                    type: string
                    format: uuid
                    description: Unique identifier of the API Log event in Payrails.
                  createdAt:
                    type: string
                    format: date-time
                    description: Exact date and time when the API Log event happened.
                  requestID:
                    type: string
                    format: uuid
                    description: Unique identifier of the API request.
                  method:
                    type: string
                    description: Request HTTP method.
                  statusCode:
                    type: number
                    description: Response HTTP code number.
                  rawRequest:
                    type: string
                    description: Serialized raw request.
                  rawResponse:
                    type: string
                    description: Serialized raw response.
              examples:
                apiLogEvent:
                  description: API Log event.
                  value:
                    id: 080405df-b575-4106-9ff6-5cceafc35445
                    requestId: 0412ee01-d3e6-4cb7-a29f-e91721b0b62b
                    createdAt: '2023-05-23T14:12:40.444493Z'
                    endpointUrl: /payment/providers/070dacf4-ddd8-42cd-87ec-944ebf1adc41/proxy
                    statusCode: 404
                    method: POST
                    rawRequest: '{"body":{"body":{"amount":{"currency":"USD","value":1000},"merchantAccount":"YOUR_MERCHANT_ACCOUNT","paymentMethod":{"cvc":"***","expiryMonth":"{{cardExpiryMonth}}","expiryYear":"{{cardExpiryYear}}","holderName":"{{cardHolderName}}","number":"***","type":"scheme"},"reference":"your-order-number","returnUrl":"https://your-company.com/..."},"headers":{"Accept":"application/json","Content-Type":"application/json","x-API-key":"YOUR_API_KEY"},"paymentInstrumentId":"eeaac45c-f032-49bc-a8c5-ec99d79b74e2","providerConfigId":"d9699acd-9361-4e11-8d06-b30f41fc6210"},"headers":{"Accept":"application/json","Accept-Encoding":"gzip","Authorization":"***","Cdn-Loop":"cloudflare","Cf-Connecting-Ip":"18.196.176.219","Cf-Ipcountry":"DE","Cf-Ray":"7cbde527aed4bbd9-FRA","Cf-Visitor":{"scheme":"https"},"Ckoidempotencykey":"application/json","Content-Length":"706","Content-Type":"application/json","Postman-Token":"bfa62b82-5026-4bb3-9b57-0930f287fccc","True-Client-Ip":"18.196.176.219","User-Agent":"PostmanRuntime/7.29.3","X-Forwarded-For":"172.70.247.146","X-Forwarded-Host":"payrails-api.staging.payrails.io","X-Forwarded-Port":"443","X-Forwarded-Proto":"https","X-Forwarded-Scheme":"https","X-Idempotency-Key":"5ff04085-beae-4d41-ba78-73eb918d8e7c","X-Original-Forwarded-For":"18.196.176.219","X-Real-Ip":"172.70.247.146","X-Request-Id":"0412ee01-d3e6-4cb7-a29f-e91721b0b62b","X-Scheme":"https","Xapikey":"application/json"}}'
                    rawResponse: '{"body":{"errors":[{"detail":"The resource with ''Payment instrument ID'': ''eeaac45c-f032-49bc-a8c5-ec99d79b74e2'' was not found.","id":"6a1456fc-13cf-4b8a-a75e-3891d86873a0","title":"resource.not-found"}]},"headers":{"Content-Type":"application/json; charset=UTF-8","X-Request-Id":"0412ee01-d3e6-4cb7-a29f-e91721b0b62b"}}'
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.malformed
                    detail: The request has malformed syntax
                    docUrl: https://docs.payrails.com/docs/error-codes#requestmalformed
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.unauthorized
                    detail: The request lacks necessary credentials to perform the specified action
                    docUrl: https://docs.payrails.com/docs/error-codes#requestunauthorized
        '403':
          description: Insufficient Scope.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: e7db22b3-914e-4975-928e-9edfb0885bea
                    code: request.forbidden
                    detail: The request credentials lack the required permissions to perform the specified action
                    docUrl: https://docs.payrails.com/docs/error-codes#requestforbidden
        '404':
          description: Not Found.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.not-found
                    detail: The requested resource was not found
                    docUrl: https://docs.payrails.com/docs/error-codes#requestnot-found
        '429':
          description: Too Many Requests.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.rate-limit
                    detail: Too many requests
                    docUrl: https://docs.payrails.com/docs/error-codes#requestrate-limit
components:
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: x-api-key
      description: |
        You can use your secret API key in the `x-api-key` header of your API requests for supported endpoints: `x-api-key: <YOUR_API_KEY_HERE>`.
        API keys are environment specific and should be securely guarded.

        You don't have your API key yet? Contact your Payrails account manager.
    BearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        You can use an OAuth2 JWT bearer token in the `Authorization` header of your API requests for supported endpoints: `Authorization: Bearer <YOUR_JWT_HERE>`.
        These tokens are valid for 10 minutes and can be requested via the [access token endpoint](#operation/getOAuthToken) endpoint.
    BearerVaultClientToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        You can use an OAuth2 JWT bearer token in the `Authorization` header of your API requests for supported endpoints: `Authorization: Bearer <YOUR_JWT_HERE>`.
        These tokens are valid for 10 minutes and can be requested via the [vault client init](#operation/vaultClientInit) endpoint.
