openapi: 3.1.0
info:
  version: 1.3.15
  title: Payrails API Reference
  contact:
    name: Payrails
    url: https://www.payrails.com
    email: tech@payrails.com
  license:
    name: Payrails GmbH
    url: https://www.payrails.com/
  description: |
    ---
    Payrails provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes. You can consume the APIs directly using your favorite HTTP/REST library.
servers:
  - url: https://api.staging.payrails.io
    description: Payrails environment.
security:
  - ApiKey: []
tags:
  - name: BinLookup
    description: Operations related to getting information about a card by its BIN (or IIN).
paths:
  /payment/binLookup/{bin}:
    get:
      operationId: getBinLookup
      summary: Get issuer info by BIN
      description: Provides card issuer information based on a bank identification number (BIN) or issuer identification number (IIN).
      tags:
        - BinLookup
      security:
        - BearerToken:
            - bin:read
      parameters:
        - name: bin
          in: path
          required: true
          schema:
            type: string
            minLength: 6
            maxLength: 8
            description: First 6-8 digits of the Card number. Also known as IIN (Issuer Identification Number).
            example: '416598'
          description: BIN (or IIN) to lookup.
      responses:
        '200':
          description: Created.
          content:
            application/json:
              schema:
                type: object
                description: Information about an issuer by the given BIN (or IIN).
                required:
                  - bin
                properties:
                  bin:
                    type: string
                    minLength: 6
                    maxLength: 8
                    description: First 6-8 digits of the Card number. Also known as IIN (Issuer Identification Number).
                    example: '416598'
                  network:
                    type: string
                    description: Network of the instrument.
                    enum:
                      - unspecified
                      - visa
                      - visadankort
                      - mastercard
                      - amex
                      - diners
                      - discover
                      - unionpay
                      - unionpayuzcard
                      - maestro
                      - maestrobancontact
                      - hipercard
                      - jcb
                      - jcblankapay
                      - argencard
                      - aura
                      - belkart
                      - bpfuelcard
                      - cabal
                      - carnet
                      - cirrus
                      - chjonesfuelcard
                      - uzcard
                      - codensa
                      - dankort
                      - dinacard
                      - duet
                      - ebt
                      - eftpos
                      - elo
                      - euroshellfuelcard
                      - gecapital
                      - bc
                      - hrgstore
                      - humo
                      - lankapay
                      - lukoilfuelcard
                      - bancontact
                      - meeza
                      - newday
                      - mir
                      - ourocard
                      - pagobancomat
                      - paypak
                      - paypal
                      - phhfuelcard
                      - prostir
                      - rupay
                      - sbercard
                      - sodexo
                      - starrewards
                      - cencosud
                      - naranja
                      - troy
                      - uatp
                      - ukfuelcard
                      - verve
                      - voyager
                      - vpay
                      - wex
                      - cmi
                      - atm
                      - bankcard
                      - localbrand
                      - loyalty
                      - privatelabel
                      - fuelcard
                      - redfuelcard
                      - redliquidfuelcard
                  localNetwork:
                    description: Card local network that supports the card, e.g. CartesBancaires, Dankort, Mada, Bancontact.
                    type: string
                    enum:
                      - bancontact
                      - cartesbancaires
                      - dankort
                      - mada
                  issuer:
                    type: string
                    description: Name of the bank or institution that issued the card.
                  issuerCountry:
                    description: Country of the bank or institution that issued the card.
                    type: object
                    required:
                      - code
                    properties:
                      code:
                        type: string
                        description: ISO 3166-1 alpha-2 country code.
                        pattern: ^[A-Z]{2}$
                      iso3:
                        type: string
                        description: ISO 3-letter country code. Returned by Payrails, but not interpreted in requests.
                        pattern: ^[A-Z]{3}$
                      name:
                        type: string
                        description: The English name of the country. Returned by Payrails, but not interpreted in requests.
                  segment:
                    type: string
                    description: Segment of the card, e.g. gold, black, business.
                  type:
                    type: string
                    description: Type of the card, e.g. credit, debit, prepaid, gift.
                  typeDetails:
                    type: string
                    description: More information about the card type, e.g. personal, commercial.
                  isNetworkToken:
                    type: boolean
                    description: |
                      Indicates whether the card credential represents a network token rather than a primary account number (PAN).
                  isFlexCard:
                    type: boolean
                    description: |
                      Indicates whether the card is enrolled in a Flexible Credential or Flex Card program supported by the network - e.g. Visa Flexible Credential, Mastercard FlexCard.
              example:
                bin: '416598'
                network: visa
                localNetwork: bancontact
                issuer: Revolut
                issuerCountry:
                  code: LT
                  name: Lithuania
                  iso3: LTU
                segment: infinite
                type: debit
                typeDetails: personal
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.malformed
                    detail: The request has malformed syntax
                    docUrl: https://docs.payrails.com/docs/error-codes#requestmalformed
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.unauthorized
                    detail: The request lacks necessary credentials to perform the specified action
                    docUrl: https://docs.payrails.com/docs/error-codes#requestunauthorized
        '403':
          description: Insufficient Scope.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: e7db22b3-914e-4975-928e-9edfb0885bea
                    code: request.forbidden
                    detail: The request credentials lack the required permissions to perform the specified action
                    docUrl: https://docs.payrails.com/docs/error-codes#requestforbidden
        '404':
          description: Not Found.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.not-found
                    detail: The requested resource was not found
                    docUrl: https://docs.payrails.com/docs/error-codes#requestnot-found
        '429':
          description: Too Many Requests.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.rate-limit
                    detail: Too many requests
                    docUrl: https://docs.payrails.com/docs/error-codes#requestrate-limit
components:
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: x-api-key
      description: |
        You can use your secret API key in the `x-api-key` header of your API requests for supported endpoints: `x-api-key: <YOUR_API_KEY_HERE>`.
        API keys are environment specific and should be securely guarded.

        You don't have your API key yet? Contact your Payrails account manager.
    BearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        You can use an OAuth2 JWT bearer token in the `Authorization` header of your API requests for supported endpoints: `Authorization: Bearer <YOUR_JWT_HERE>`.
        These tokens are valid for 10 minutes and can be requested via the [access token endpoint](#operation/getOAuthToken) endpoint.
    BearerVaultClientToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        You can use an OAuth2 JWT bearer token in the `Authorization` header of your API requests for supported endpoints: `Authorization: Bearer <YOUR_JWT_HERE>`.
        These tokens are valid for 10 minutes and can be requested via the [vault client init](#operation/vaultClientInit) endpoint.
