openapi: 3.1.0
info:
  version: 1.3.15
  title: Payrails API Reference
  contact:
    name: Payrails
    url: https://www.payrails.com
    email: tech@payrails.com
  license:
    name: Payrails GmbH
    url: https://www.payrails.com/
  description: |
    ---
    Payrails provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes. You can consume the APIs directly using your favorite HTTP/REST library.
servers:
  - url: https://api.staging.payrails.io
    description: Payrails environment.
security:
  - ApiKey: []
tags:
  - name: Holders
    description: A Holder is a group of accounts that belong together with specific criteria, linked to their payment instruments and identities. For example, it can represent a digital wallet for a person, where they store balance that they top up, refunded orders, referral bonuses, etc.
paths:
  /merchant/holders:
    get:
      tags:
        - Holders
      summary: Search & list holders
      description: Search & list holders.
      operationId: listHolders
      security:
        - BearerToken:
            - holders:list
      parameters:
        - name: filter[reference]
          in: query
          schema:
            type: string
          description: Filter holders by reference.
        - name: filter[id]
          in: query
          schema:
            type: string
          description: Filter holders by ID.
        - name: filter[status]
          in: query
          schema:
            type: string
          description: Filter holders by a list of statuses.
        - name: page[after]
          in: query
          description: Search collection items after that cursor.
          required: false
          schema:
            type: string
            description: Cursor for paging results.
          example: xk2h55zsy5
        - name: page[before]
          in: query
          description: Search collection items before that cursor.
          required: false
          schema:
            type: string
            description: Cursor for paging results.
          example: 9wkueqcavq
        - name: page[size]
          in: query
          description: Length of the collection to search.
          required: false
          schema:
            type: integer
            format: int32
          example: 20
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                type: object
                required:
                  - links
                  - results
                properties:
                  links:
                    required:
                      - self
                    properties:
                      self:
                        type: string
                      prev:
                        type: string
                      next:
                        type: string
                      first:
                        type: string
                      last:
                        type: string
                  results:
                    type: array
                    items:
                      type: object
                      required:
                        - id
                        - reference
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the Holder in Payrails.
                        reference:
                          type: string
                          description: Merchant-provided reference for the transaction counterparty, i.e. the paying consumer.
                        createdAt:
                          type: string
                          format: date-time
                          description: Date and time when the Holder was created.
                        status:
                          type: array
                          items:
                            type: string
                          uniqueItems: true
                          description: Status of the Holder in Payrails.
                        type:
                          type: string
                          description: Value of merchant-defined enumeration of Holder Types.
              example:
                links:
                  self: https://api.staging.payrails.io/merchant/holders?page[after]=qf7pnbyfrr&page[size]=2
                  prev: https://api.staging.payrails.io/merchant/holders?page[before]=hbe66nh8i8&page[size]=2
                  next: https://api.staging.payrails.io/merchant/holders?page[after]=xk2h55zsy5&page[size]=2
                  first: https://api.staging.payrails.io/merchant/holders?page[size]=2
                  last: https://api.staging.payrails.io/merchant/holders?page[before]=9wkueqcavq&page[size]=2
                results:
                  - id: b8fe6271-5d71-4d28-b8e8-89e64acc0c49
                    reference: user-123
                    createdAt: '2022-02-03T14:38:40.557Z'
                    status:
                      - enabled
                    type: Customer
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.unauthorized
                    detail: The request lacks necessary credentials to perform the specified action
                    docUrl: https://docs.payrails.com/docs/error-codes#requestunauthorized
        '403':
          description: Insufficient Scope.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: e7db22b3-914e-4975-928e-9edfb0885bea
                    code: request.forbidden
                    detail: The request credentials lack the required permissions to perform the specified action
                    docUrl: https://docs.payrails.com/docs/error-codes#requestforbidden
    post:
      tags:
        - Holders
      summary: Create a holder
      description: Create a holder.
      operationId: createHolder
      security:
        - BearerToken:
            - holders:create
      parameters:
        - name: x-idempotency-key
          in: header
          description: |
            Idempotency key to be used.
            Sending again the same key would return the same result without re-executing the update.
          required: true
          schema:
            type: string
            format: uuid
          example: 91874e4d-81e9-4486-aee4-ee1de84da890
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - reference
              properties:
                reference:
                  type: string
                  description: Merchant-specific reference for the Holder. Usually mapped to the user ID in the merchant's system.
                type:
                  type: string
                  description: Value of merchant-defined enumeration of Holder Types.
            example:
              reference: customer-123
              type: Customer
      responses:
        '201':
          description: Created.
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                  - reference
                properties:
                  id:
                    type: string
                    format: uuid
                    description: Unique identifier of the Holder in Payrails.
                  reference:
                    type: string
                    description: Merchant-provided reference for the transaction counterparty, i.e. the paying consumer.
                  createdAt:
                    type: string
                    format: date-time
                    description: Date and time when the Holder was created.
                  status:
                    type: array
                    items:
                      type: string
                    uniqueItems: true
                    description: Status of the Holder in Payrails.
                  type:
                    type: string
                    description: Value of merchant-defined enumeration of Holder Types.
              example:
                id: b8fe6271-5d71-4d28-b8e8-89e64acc0c49
                reference: user-123
                createdAt: '2022-02-03T14:38:40.557Z'
                status:
                  - enabled
                type: Customer
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.malformed
                    detail: The request has malformed syntax
                    docUrl: https://docs.payrails.com/docs/error-codes#requestmalformed
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.unauthorized
                    detail: The request lacks necessary credentials to perform the specified action
                    docUrl: https://docs.payrails.com/docs/error-codes#requestunauthorized
        '403':
          description: Insufficient Scope.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: e7db22b3-914e-4975-928e-9edfb0885bea
                    code: request.forbidden
                    detail: The request credentials lack the required permissions to perform the specified action
                    docUrl: https://docs.payrails.com/docs/error-codes#requestforbidden
        '404':
          description: Not Found.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.not-found
                    detail: The requested resource was not found
                    docUrl: https://docs.payrails.com/docs/error-codes#requestnot-found
  /merchant/holders/{holderId}:
    get:
      summary: Get a holder by ID
      operationId: getHolder
      description: Get a holder for the given id.
      tags:
        - Holders
      security:
        - BearerToken:
            - holders:read
      parameters:
        - name: holderId
          in: path
          description: Identifier of the resource in Payrails.
          required: true
          schema:
            type: string
            format: uuid
          example: d5454c2f-ae5e-44f3-8edf-f6dad64f005f
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                  - reference
                properties:
                  id:
                    type: string
                    format: uuid
                    description: Unique identifier of the Holder in Payrails.
                  reference:
                    type: string
                    description: Merchant-provided reference for the transaction counterparty, i.e. the paying consumer.
                  createdAt:
                    type: string
                    format: date-time
                    description: Date and time when the Holder was created.
                  status:
                    type: array
                    items:
                      type: string
                    uniqueItems: true
                    description: Status of the Holder in Payrails.
                  type:
                    type: string
                    description: Value of merchant-defined enumeration of Holder Types.
              example:
                id: b8fe6271-5d71-4d28-b8e8-89e64acc0c49
                reference: user-123
                createdAt: '2022-02-03T14:38:40.557Z'
                status:
                  - enabled
                type: Customer
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.malformed
                    detail: The request has malformed syntax
                    docUrl: https://docs.payrails.com/docs/error-codes#requestmalformed
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.unauthorized
                    detail: The request lacks necessary credentials to perform the specified action
                    docUrl: https://docs.payrails.com/docs/error-codes#requestunauthorized
        '403':
          description: Insufficient Scope.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: e7db22b3-914e-4975-928e-9edfb0885bea
                    code: request.forbidden
                    detail: The request credentials lack the required permissions to perform the specified action
                    docUrl: https://docs.payrails.com/docs/error-codes#requestforbidden
        '404':
          description: Not Found.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.not-found
                    detail: The requested resource was not found
                    docUrl: https://docs.payrails.com/docs/error-codes#requestnot-found
        '429':
          description: Too Many Requests.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.rate-limit
                    detail: Too many requests
                    docUrl: https://docs.payrails.com/docs/error-codes#requestrate-limit
components:
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: x-api-key
      description: |
        You can use your secret API key in the `x-api-key` header of your API requests for supported endpoints: `x-api-key: <YOUR_API_KEY_HERE>`.
        API keys are environment specific and should be securely guarded.

        You don't have your API key yet? Contact your Payrails account manager.
    BearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        You can use an OAuth2 JWT bearer token in the `Authorization` header of your API requests for supported endpoints: `Authorization: Bearer <YOUR_JWT_HERE>`.
        These tokens are valid for 10 minutes and can be requested via the [access token endpoint](#operation/getOAuthToken) endpoint.
    BearerVaultClientToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        You can use an OAuth2 JWT bearer token in the `Authorization` header of your API requests for supported endpoints: `Authorization: Bearer <YOUR_JWT_HERE>`.
        These tokens are valid for 10 minutes and can be requested via the [vault client init](#operation/vaultClientInit) endpoint.
