openapi: 3.1.0
info:
  version: 1.3.15
  title: Payrails API Reference
  contact:
    name: Payrails
    url: https://www.payrails.com
    email: tech@payrails.com
  license:
    name: Payrails GmbH
    url: https://www.payrails.com/
  description: |
    ---
    Payrails provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes. You can consume the APIs directly using your favorite HTTP/REST library.
servers:
  - url: https://api.staging.payrails.io
    description: Payrails environment.
security:
  - ApiKey: []
tags:
  - name: Vault Display SDK
    description: Operations related to DisplaySDK.
paths:
  /token/client/init:
    post:
      summary: Initialize a Vault Client SDK
      operationId: vaultClientInit
      description: |
        Fetch the necessary information to initialize Display cards SDK on your client.
      security:
        - BearerToken:
            - vaultconfigs:read:client
      tags:
        - Vault Display SDK
      requestBody:
        description: Use the Reveal operation to display card data stored in your vault within Payrails secure and compliant iframe.
        content:
          application/json:
            schema:
              type: object
              title: Request to get the necessary information used to initialize the client SDK.
              allOf:
                - type: object
                  anyOf:
                    - type: object
                      title: Reveal.
                      allOf:
                        - type: object
                          required:
                            - type
                            - auditData
                          properties:
                            type:
                              type: string
                              description: |
                                The type of client side elements that you need a configuration for `reveal`. Reveal allows you to securely display record fields stored in Payrails Vault, e.g. card data. This feature is only available by request and requires an approval by Payrails.
                              enum:
                                - reveal
                            auditData:
                              type: string
                              description: |
                                Data required for an audit trail related to the request to display the fields. E.g. user ID, who requested to display data, reason, etc.
                        - type: object
                          anyOf:
                            - type: object
                              title: By record.
                              required:
                                - record
                              properties:
                                record:
                                  type: object
                                  allOf:
                                    - type: object
                                      properties:
                                        fields:
                                          type: array
                                          description: |
                                            Record field types allowed for display. Possible fields are depended on a record type, e.g. for record type `card` it can be
                                            `cardNumber`, `expiryMonth`, `expiryYear`, `securityCode`, `holderName`.
                                          items:
                                            type: string
                                    - type: object
                                      anyOf:
                                        - type: object
                                          title: By ID.
                                          required:
                                            - id
                                          properties:
                                            id:
                                              type: string
                                              format: uuid
                                              description: Payrails unique identifier of a record.
                                        - type: object
                                          title: By alias.
                                          required:
                                            - alias
                                          properties:
                                            alias:
                                              type: string
                                              description: Alias of a record field.
                            - type: object
                              title: By aliases.
                              required:
                                - aliases
                              properties:
                                aliases:
                                  type: array
                                  description: List of record field aliases.
                                  items:
                                    type: string
                            - type: object
                              title: By instrument ID.
                              required:
                                - instrumentId
                              properties:
                                instrumentId:
                                  type: string
                                  format: uuid
                                  description: Unique identifier of an instrument.
            examples:
              ByRecordID:
                description: By record ID.
                value:
                  type: reveal
                  auditData: Max Mustermann, Hotel City Express, Branch Manager
                  record:
                    id: 9d113e2a-35a0-40e1-828b-35a18ac35b41
                    fields:
                      - cardNumber
                      - securityCode
              ByRecordFieldAlias:
                description: By record field alias.
                value:
                  type: reveal
                  auditData: Max Mustermann, Hotel City Express, Branch Manager
                  record:
                    alias: field_XYZ
                    fields:
                      - cardNumber
                      - securityCode
              ByFieldAliases:
                description: By list of record field aliases.
                value:
                  type: reveal
                  auditData: Max Mustermann, Hotel City Express, Branch Manager
                  aliases:
                    - field_ABC
                    - field_XYZ
              ByInstrumentID:
                description: By instrument ID.
                value:
                  type: reveal
                  auditData: Max Mustermann, Hotel City Express, Branch Manager
                  instrumentId: 1099a80d-b8a9-41bf-bda2-6f5df639d824
                  record:
                    fields:
                      - cardNumber
                      - securityCode
      responses:
        '200':
          description: OK. Configurations to initialize Payrails SDK on your client.
          content:
            application/json:
              schema:
                type: object
                title: OK. Configurations to initialize Payrails SDK on your client.
                required:
                  - version
                  - data
                properties:
                  version:
                    type: string
                    description: The SDK version these configurations are compatible with.
                  data:
                    type: string
                    format: byte
                    description: Configurations to initialize the client SDK.
              example:
                version: 1.2.3
                data: TG9yZW0gaXBzdW0gZG9sb3Igc2l0IGFtZXQsIGNvbnNlY3RldHVyIGFkaXBpc2NpbmcgZWxpdCwgc2VkIGRvIGVpdXNtb2QgdGVtcG9yIGluY2lkaWR1bnQgdXQgbGFib3JlIGV0IGRvbG9yZSBtYWduYSBhbGlxdWEuIFV0IGVuaW0gYWQgbWluaW0gdmVuaWFtLCBxdWlzIG5vc3RydWQgZXhlcmNpdGF0aW9uIHVsbGFtY28gbGFib3JpcyBuaXNpIHV0IGFsaXF1aXAgZXggZWEgY29tbW9kbyBjb25zZXF1YXQuIER1aXMgYXV0ZSBpcnVyZSBkb2xvciBpbiByZXByZWhlbmRlcml0IGluIHZvbHVwdGF0ZSB2ZWxpdCBlc3NlIGNpbGx1bSBkb2xvcmUgZXUgZnVnaWF0IG51bGxhIHBhcmlhdHVyLiBFeGNlcHRldXIgc2ludCBvY2NhZWNhdCBjdXBpZGF0YXQgbm9uIHByb2lkZW50LCBzdW50IGluIGN1bHBhIHF1aSBvZmZpY2lhIGRlc2VydW50IG1vbGxpdCBhbmltIGlkIGVzdCBsYWJvcnVtLg==
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.malformed
                    detail: The request has malformed syntax
                    docUrl: https://docs.payrails.com/docs/error-codes#requestmalformed
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.unauthorized
                    detail: The request lacks necessary credentials to perform the specified action
                    docUrl: https://docs.payrails.com/docs/error-codes#requestunauthorized
        '403':
          description: Insufficient Scope.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: e7db22b3-914e-4975-928e-9edfb0885bea
                    code: request.forbidden
                    detail: The request credentials lack the required permissions to perform the specified action
                    docUrl: https://docs.payrails.com/docs/error-codes#requestforbidden
        '404':
          description: Not Found.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.not-found
                    detail: The requested resource was not found
                    docUrl: https://docs.payrails.com/docs/error-codes#requestnot-found
components:
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: x-api-key
      description: |
        You can use your secret API key in the `x-api-key` header of your API requests for supported endpoints: `x-api-key: <YOUR_API_KEY_HERE>`.
        API keys are environment specific and should be securely guarded.

        You don't have your API key yet? Contact your Payrails account manager.
    BearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        You can use an OAuth2 JWT bearer token in the `Authorization` header of your API requests for supported endpoints: `Authorization: Bearer <YOUR_JWT_HERE>`.
        These tokens are valid for 10 minutes and can be requested via the [access token endpoint](#operation/getOAuthToken) endpoint.
    BearerVaultClientToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        You can use an OAuth2 JWT bearer token in the `Authorization` header of your API requests for supported endpoints: `Authorization: Bearer <YOUR_JWT_HERE>`.
        These tokens are valid for 10 minutes and can be requested via the [vault client init](#operation/vaultClientInit) endpoint.
