openapi: 3.1.0
info:
  version: 1.3.15
  title: Payrails API Reference
  contact:
    name: Payrails
    url: https://www.payrails.com
    email: tech@payrails.com
  license:
    name: Payrails GmbH
    url: https://www.payrails.com/
  description: |
    ---
    Payrails provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes. You can consume the APIs directly using your favorite HTTP/REST library.
servers:
  - url: https://api.staging.payrails.io
    description: Payrails environment.
security:
  - ApiKey: []
tags:
  - name: Workspaces
    description: Operations related to managing workspaces.
paths:
  /merchant/workspaces:
    post:
      tags:
        - Workspaces
      summary: Create a workspace
      description: Create a new workspace.
      operationId: createWorkspace
      security:
        - BearerToken:
            - workspaces:create
      parameters:
        - name: x-idempotency-key
          in: header
          description: |
            Idempotency key to be used.
            Sending again the same key would return the same result without re-executing the update.
          required: true
          schema:
            type: string
            format: uuid
          example: 91874e4d-81e9-4486-aee4-ee1de84da890
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  description: Unique name of the Workspace.
                copyProviderConfig:
                  type: object
                  required:
                    - existingWorkspaceID
                  properties:
                    existingWorkspaceID:
                      type: string
                      format: uuid
                      description: Workspace ID from which we want to copy.
                copyWorkflowConfig:
                  type: object
                  required:
                    - existingWorkspaceID
                  properties:
                    existingWorkspaceID:
                      type: string
                      format: uuid
                      description: Workspace ID from which we want to copy.
                copyNotificationConfig:
                  type: object
                  required:
                    - existingWorkspaceID
                  properties:
                    existingWorkspaceID:
                      type: string
                      format: uuid
                      description: Workspace ID from which we want to copy.
                copyUsers:
                  type: object
                  required:
                    - existingWorkspaceID
                  properties:
                    existingWorkspaceID:
                      type: string
                      format: uuid
                      description: Workspace ID from which we want to copy.
            example:
              name: Default Workspace
              copyProviderConfig:
                existingWorkspaceID: 7f9f1882-a103-408d-ac96-46a7021e537a
              copyWorkflowConfig:
                existingWorkspaceID: 7f9f1882-a103-408d-ac96-46a7021e537a
              copyNotificationConfig:
                existingWorkspaceID: 7f9f1882-a103-408d-ac96-46a7021e537a
              copyUsers:
                existingWorkspaceID: 7f9f1882-a103-408d-ac96-46a7021e537a
      responses:
        '201':
          description: Success.
          content:
            application/json:
              schema:
                type: object
                required:
                  - workspace
                properties:
                  workspace:
                    type: object
                    title: Workspace
                    required:
                      - id
                      - name
                      - createdAt
                      - updatedAt
                    properties:
                      id:
                        type: string
                        description: Unique identifier of the Workspace.
                        format: uuid
                      name:
                        type: string
                        description: Unique name of the Workspace configuration.
                      createdBy:
                        type: string
                        description: Email address of the user that created the workspace.
                      updatedBy:
                        type: string
                        description: Email address of the user that updated the workspace.
                      createdAt:
                        type: string
                        format: date-time
                        description: Date of creation of the workspace configuration.
                      updatedAt:
                        type: string
                        format: date-time
                        description: Date of last update of the workspace configuration.
                  copyRequestFailures:
                    type: array
                    description: List of failures happened while copying items from existing workspace.
                    items:
                      type: object
                      required:
                        - existingWorkspaceID
                        - failureMessage
                      properties:
                        existingWorkspaceID:
                          type: string
                          format: uuid
                          description: Workspace ID from which we wanted to copy.
                        failureMessage:
                          type: string
                          description: Reason why that copy request failed.
              example:
                workspace:
                  id: b8fe6271-5d71-4d28-b8e8-89e64acc0c49
                  name: Default Workspace
                  createdAt: '2022-02-03T14:38:40.557Z'
                  updatedAt: '2022-02-03T14:38:40.557Z'
                  createdBy: john.doe@payrails.com
                copyRequestFailures:
                  - existingWorkspaceID: 7f9f1882-a103-408d-ac96-46a7021e537a
                    failureMessage: Failed to copy rulessets from existing workspaces.
                  - existingWorkspaceID: 7f9f1882-a103-408d-ac96-46a7021e537a
                    failureMessage: Failed to copy users from existing workspaces.
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.malformed
                    detail: The request has malformed syntax
                    docUrl: https://docs.payrails.com/docs/error-codes#requestmalformed
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.unauthorized
                    detail: The request lacks necessary credentials to perform the specified action
                    docUrl: https://docs.payrails.com/docs/error-codes#requestunauthorized
        '403':
          description: Insufficient Scope.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: e7db22b3-914e-4975-928e-9edfb0885bea
                    code: request.forbidden
                    detail: The request credentials lack the required permissions to perform the specified action
                    docUrl: https://docs.payrails.com/docs/error-codes#requestforbidden
        '404':
          description: Not Found.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.not-found
                    detail: The requested resource was not found
                    docUrl: https://docs.payrails.com/docs/error-codes#requestnot-found
    get:
      tags:
        - Workspaces
      summary: Fetch a list of workspaces
      description: Fetch a list of workspaces based on user permissions.
      operationId: getAllWorkspaces
      security:
        - BearerToken:
            - workspaces:list
      parameters:
        - name: filter[workspaceId]
          in: query
          description: Filter by Workspace ID.
          schema:
            type: string
        - name: filter[enabled]
          in: query
          description: Filter workspaces based on their state.
          schema:
            type: boolean
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                type: object
                required:
                  - results
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      title: Workspace
                      required:
                        - id
                        - name
                        - createdAt
                        - updatedAt
                      properties:
                        id:
                          type: string
                          description: Unique identifier of the Workspace.
                          format: uuid
                        name:
                          type: string
                          description: Unique name of the Workspace configuration.
                        createdBy:
                          type: string
                          description: Email address of the user that created the workspace.
                        updatedBy:
                          type: string
                          description: Email address of the user that updated the workspace.
                        createdAt:
                          type: string
                          format: date-time
                          description: Date of creation of the workspace configuration.
                        updatedAt:
                          type: string
                          format: date-time
                          description: Date of last update of the workspace configuration.
              example:
                results:
                  - id: b8fe6271-5d71-4d28-b8e8-89e64acc0c49
                    name: Default Workspace
                    createdAt: '2022-02-03T14:38:40.557Z'
                    updatedAt: '2022-02-03T14:38:40.557Z'
                    createdBy: john.doe@payrails.com
                  - id: 60971ce9-5a07-4391-beac-b750b06dfeab
                    name: My Workspace
                    createdAt: '2024-02-05T17:00:00.557Z'
                    updatedAt: '2024-02-05T17:00:00.557Z'
                    createdBy: my.user@payrails.com
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.malformed
                    detail: The request has malformed syntax
                    docUrl: https://docs.payrails.com/docs/error-codes#requestmalformed
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.unauthorized
                    detail: The request lacks necessary credentials to perform the specified action
                    docUrl: https://docs.payrails.com/docs/error-codes#requestunauthorized
        '403':
          description: Insufficient Scope.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: e7db22b3-914e-4975-928e-9edfb0885bea
                    code: request.forbidden
                    detail: The request credentials lack the required permissions to perform the specified action
                    docUrl: https://docs.payrails.com/docs/error-codes#requestforbidden
        '404':
          description: Not Found.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.not-found
                    detail: The requested resource was not found
                    docUrl: https://docs.payrails.com/docs/error-codes#requestnot-found
  /merchant/workspaces/bulk-create:
    post:
      tags:
        - Workspaces
      summary: Create workspaces
      description: Create workspaces in bulk.
      operationId: createWorkspaces
      security:
        - BearerToken:
            - workspaces:create
      parameters:
        - name: x-idempotency-key
          in: header
          description: |
            Idempotency key to be used.
            Sending again the same key would return the same result without re-executing the update.
          required: true
          schema:
            type: string
            format: uuid
          example: 91874e4d-81e9-4486-aee4-ee1de84da890
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - names
              properties:
                names:
                  type: array
                  description: Unique name of the Workspaces.
                  items:
                    type: string
                renameDefault:
                  type: boolean
                  description: If the default workspace should be renamed with first entry.
            example:
              names:
                - Europe Workspace
                - Asia Workspace
              renameDefault: false
      responses:
        '201':
          description: Success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  createdWorkspaces:
                    type: array
                    items:
                      type: object
                      title: Workspace
                      required:
                        - id
                        - name
                        - createdAt
                        - updatedAt
                      properties:
                        id:
                          type: string
                          description: Unique identifier of the Workspace.
                          format: uuid
                        name:
                          type: string
                          description: Unique name of the Workspace configuration.
                        createdBy:
                          type: string
                          description: Email address of the user that created the workspace.
                        updatedBy:
                          type: string
                          description: Email address of the user that updated the workspace.
                        createdAt:
                          type: string
                          format: date-time
                          description: Date of creation of the workspace configuration.
                        updatedAt:
                          type: string
                          format: date-time
                          description: Date of last update of the workspace configuration.
                  failedWorkspaces:
                    type: array
                    items:
                      type: object
                      required:
                        - name
                        - errorMessage
                      properties:
                        name:
                          type: string
                          description: Name of the workspace.
                        errorMessage:
                          type: string
                          description: Error due to which workspace creation failed.
              example:
                createdWorkspaces:
                  - id: b8fe6271-5d71-4d28-b8e8-89e64acc0c49
                    name: Europe Workspace
                    createdAt: '2022-02-03T14:38:40.557Z'
                    updatedAt: '2022-02-03T14:38:40.557Z'
                    createdBy: john.doe@payrails.com
                  - id: 7f9f1882-a103-408d-ac96-46a7021e537a
                    name: Asia Workspace
                    createdAt: '2022-02-03T14:38:40.557Z'
                    updatedAt: '2022-02-03T14:38:40.557Z'
                    createdBy: john.doe@payrails.com
                failedWorkspaces:
                  - name: America Workspace
                    errorMessage: Failed to create workspace.
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.malformed
                    detail: The request has malformed syntax
                    docUrl: https://docs.payrails.com/docs/error-codes#requestmalformed
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.unauthorized
                    detail: The request lacks necessary credentials to perform the specified action
                    docUrl: https://docs.payrails.com/docs/error-codes#requestunauthorized
        '403':
          description: Insufficient Scope.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: e7db22b3-914e-4975-928e-9edfb0885bea
                    code: request.forbidden
                    detail: The request credentials lack the required permissions to perform the specified action
                    docUrl: https://docs.payrails.com/docs/error-codes#requestforbidden
        '404':
          description: Not Found.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.not-found
                    detail: The requested resource was not found
                    docUrl: https://docs.payrails.com/docs/error-codes#requestnot-found
  /merchant/workspaces/{workspaceId}:
    get:
      summary: Get a workspace by ID
      operationId: getWorkspace
      description: Get a workspace for the given ID.
      tags:
        - Workspaces
      security:
        - BearerToken:
            - workspaces:list
      parameters:
        - name: workspaceId
          in: path
          description: Identifier of the resource in Payrails.
          required: true
          schema:
            type: string
            format: uuid
          example: d5454c2f-ae5e-44f3-8edf-f6dad64f005f
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                type: object
                title: Workspace
                required:
                  - id
                  - name
                  - createdAt
                  - updatedAt
                properties:
                  id:
                    type: string
                    description: Unique identifier of the Workspace.
                    format: uuid
                  name:
                    type: string
                    description: Unique name of the Workspace configuration.
                  createdBy:
                    type: string
                    description: Email address of the user that created the workspace.
                  updatedBy:
                    type: string
                    description: Email address of the user that updated the workspace.
                  createdAt:
                    type: string
                    format: date-time
                    description: Date of creation of the workspace configuration.
                  updatedAt:
                    type: string
                    format: date-time
                    description: Date of last update of the workspace configuration.
              example:
                id: b8fe6271-5d71-4d28-b8e8-89e64acc0c49
                name: My Workspace
                createdAt: '2022-02-03T14:38:40.557Z'
                updatedAt: '2022-02-03T14:38:40.557Z'
                createdBy: john.doe@payrails.com
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.malformed
                    detail: The request has malformed syntax
                    docUrl: https://docs.payrails.com/docs/error-codes#requestmalformed
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.unauthorized
                    detail: The request lacks necessary credentials to perform the specified action
                    docUrl: https://docs.payrails.com/docs/error-codes#requestunauthorized
        '403':
          description: Insufficient Scope.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: e7db22b3-914e-4975-928e-9edfb0885bea
                    code: request.forbidden
                    detail: The request credentials lack the required permissions to perform the specified action
                    docUrl: https://docs.payrails.com/docs/error-codes#requestforbidden
        '404':
          description: Not Found.
          content:
            application/json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      description: Error struct that includes the error, cause, reason, and possible resolutions. Check the full documentation [here](https://docs.payrails.com/docs/error-codes#error-structure).
                      required:
                        - id
                        - code
                        - detail
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the error. Please use this value when reporting an issue to our team, so we can help you faster.
                        code:
                          type: string
                          description: Machine-friendly error code assigned to the error. Check the full list of possible values [here](https://docs.payrails.com/docs/error-codes#list-of-error-codes).
                        detail:
                          type: string
                          description: Human-readable description about the error, its cause, and resolution.
                        docUrl:
                          type: string
                          description: Link to the specific documentation about this particular `code`.
                        reason:
                          type: object
                          additionalProperties: true
                          description: Metadata providing more details about the reason of the error. The structure of this object varies according to the `code`.
              example:
                errors:
                  - id: a24bc325-3929-4d9d-9c08-b3aa532685b7
                    code: request.not-found
                    detail: The requested resource was not found
                    docUrl: https://docs.payrails.com/docs/error-codes#requestnot-found
components:
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: x-api-key
      description: |
        You can use your secret API key in the `x-api-key` header of your API requests for supported endpoints: `x-api-key: <YOUR_API_KEY_HERE>`.
        API keys are environment specific and should be securely guarded.

        You don't have your API key yet? Contact your Payrails account manager.
    BearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        You can use an OAuth2 JWT bearer token in the `Authorization` header of your API requests for supported endpoints: `Authorization: Bearer <YOUR_JWT_HERE>`.
        These tokens are valid for 10 minutes and can be requested via the [access token endpoint](#operation/getOAuthToken) endpoint.
    BearerVaultClientToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        You can use an OAuth2 JWT bearer token in the `Authorization` header of your API requests for supported endpoints: `Authorization: Bearer <YOUR_JWT_HERE>`.
        These tokens are valid for 10 minutes and can be requested via the [vault client init](#operation/vaultClientInit) endpoint.
